const express = require("express");
const products = require("../components/products/product-routes");
const users = require("../components/users/routes");
const diets = require("../components/diets/diet-routes");
const dietDays = require("../components/dietDays/diet-days-routes");
const meals = require("../components/meals/meal-routes");
const customProducts = require("../components/customProducts/custom-product-routes");
const recipes = require("../components/recipes/recipe-routes");
const customRecipes = require("../components/customRecipes/custom-recipe-routes");
const customExercises = require("../components/customExercises/custom-exercise-routes");
const workouts = require("../components/workouts/workout-routes");
const tables = require("../components/tables/table-routes");
const splits = require("../components/splits/split-routes");
const exercises = require("../components/exercises/exercise-routes");
const sets = require("../components/sets/set-routes");
const auth = require("../components/auth/auth-routes");
const logs = require("../components/util/logs-routes");
const billing = require("../components/billing/billing-routes");
const appVersion = require("../components/appVersion/app-version-routes");
const envManager = require("../components/envManager/env-manager-routes");
const serverManager = require("../components/serverManager/server-manager-routes");
const gitManager = require("../components/gitManager/git-manager-routes");
const pinnedExerciseNotes = require("../components/pinnedExerciseNotes/pinned-exercise-note-routes");
const anthropometry = require("../components/anthropometry/anthropometry-routes");
const nutritionalGoals = require("../components/nutritionalGoals/nutritional-goal-routes");
const remoteConfig = require("../components/remoteConfig/remote-config-routes");
const trainerClients = require("../components/trainerClients/trainer-client-routes");
const trainerIntakeConfig = require("../components/trainerIntakeConfig/trainer-intake-config-routes");
const workoutTemplates = require("../components/workoutTemplates/workout-template-routes");
const dietTemplates = require("../components/dietTemplates/diet-template-routes");
const planAssignments = require("../components/planAssignments/plan-assignment-routes");
const nutritionPreferences = require("../components/nutritionPreferences/nutrition-preferences-routes");
const nutritionPreferencesTrainer = require("../components/nutritionPreferences/nutrition-preferences-trainer-routes");
const mealSnippets = require("../components/mealSnippets/meal-snippet-routes");
const mealProposals = require("../components/mealProposals/meal-proposal-routes");
const trainerCheckins = require("../components/trainerCheckins/checkin-routes");
const trainerTasks = require("../components/trainerTasks/trainer-task-routes");
const notifications = require("../components/notifications/notification-routes");
const coachDashboard = require("../components/coachDashboard/coach-dashboard-routes");
const trainerSubscription = require("../components/trainerSubscription/trainer-subscription-routes");

const router = express.Router();

router.use("/auth", auth);
router.use("/products", products);
router.use("/users", users);
router.use("/diets", diets);
router.use("/dietdays", dietDays);
router.use("/meals", meals);
router.use("/customproducts", customProducts);
router.use("/recipes", recipes);
router.use("/customrecipes", customRecipes);
router.use("/customexercises", customExercises);
router.use("/tables", tables);
router.use("/splits", splits);
router.use("/workouts", workouts);
router.use("/exercises", exercises);
router.use("/sets", sets);
router.use("/logs", logs);
router.use("/billing", billing);
router.use("/pinned-exercise-notes", pinnedExerciseNotes);
router.use("/app", appVersion);
router.use("/env", envManager);
router.use("/server", serverManager);
router.use("/git", gitManager);
router.use("/anthropometry", anthropometry);
router.use("/nutritionalgoals", nutritionalGoals);
router.use("/config", remoteConfig);
router.use("/trainer", trainerClients);
router.use("/trainer", trainerIntakeConfig);
router.use("/trainer", workoutTemplates);
router.use("/trainer", dietTemplates);
router.use("/trainer", planAssignments);
router.use("/nutrition-preferences", nutritionPreferences);
router.use("/trainer", nutritionPreferencesTrainer);
router.use("/trainer", mealSnippets);
router.use("/trainer", mealProposals.trainerRouter);
router.use(mealProposals.clientRouter);
router.use("/trainer", trainerCheckins.trainerRouter);
router.use(trainerCheckins.clientRouter);
router.use("/trainer", trainerTasks.trainerRouter);
router.use(trainerTasks.clientRouter);
router.use(notifications);
router.use("/trainer", coachDashboard);
router.use("/trainer", trainerSubscription);

module.exports = router;
